server:
  port: 8080
target:
  url: ${SCRAPPING_URL:https://jobs.techstars.com}
  endpoint: ${SCRAPPING_ENDPOINT:/jobs?filter=}
spring:
  h2:
    console:
      enabled: true
      path: ${H2_CONSOLE_ENDPOINT:/db}
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ${DATABASE_USERNAME:1}
    password: ${DATABASE_PASSWORD:1}
springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/ui}
